### ISSUE TITLE
Bar code detection problem

### ISSUE THREAD

**Issue by srijana-ya** [foundation-for-environmental-monitoring/ffem-lite#10]
The app is no longer detecting the bar code for Asus Zenfone and Samsung G5 even after uninstalling and installing it again with the new update even though both seem to be running on the Alpha 0.20 version.
The format also does not align or detect for phones like honor AL30(display 5.99 inches) and Redmi Note 6 Pro(display 6.26 inches)

**Comment by nhternup** [comment]
Comment copied over from Issue #11 :

The app is giving bad lighting (with and without torch) and crashes most of the time on Asus Zenfone(ASUS_X008DA) and honor(LND-AL30) .
On Redmi Note 6 pro, the app does give results but crashes once in a while.
(Test Images Uploaded)

**Comment by nhternup** [comment]
Comment copied over from Issue #12 :

With the new portrait mode, the error is always shown as "Bad Lighting" in Redmi Note 6 Pro and the image so received is sliced into half, images of which has been uploaded on the Test folder(Cl_RedmiNote6Pro_std_BadLighting).
To be noted: The bar-code has never been detected by this phone and the capture button is being used while analyzing as of now.
-The app is also continuously crashing once in a while on Samsung On5 and Redmi Note 6 pro.

**Comment by srijana-ya** [comment]
Alpha - 0.23 keeps crashing as soon as the bar code is detected on Redmi Note 6 pro and Moto G.

**Comment by srijana-ya** [comment]
Alpha- 0.24 has given better results altogether but Redmi Note 6 Pro still keeps crashing as soon as the bar code is detected. As such the swatches aren't detected and hence give no value. Also, the detected image caught in alpha- 0.24 in Redmi Note 6 Pro seems to be blurry as compared to the previous versions. Test images and a video of Redmi Note 6 Pro crashing uploaded in the test folder in the drive.

**Comment by srijana-ya** [comment]
Calibration Errors occurring on Lenovo XT1902 with pH, test images uploaded.

**Comment by srijana-ya** [comment]
Redmi Note 6 Pro still crashing with Alpha-0.25. The same error as before. Images uploaded in the drive.

**Comment by srijana-ya** [comment]
While using the manual capture button on Asus_X008DA, the extracted image with the swatch and cuvette detection isn't shown and only a full image can be viewed which makes it harder to analyze if the swatches are being detected correctly. (Note: The phone does give results and there is no error except for the fact that the barcode is not automatically detected so need for manual capture). 
Full images uploaded in the drive.

Could the barcode detection time be reduced a bit?

Redmi Note 6 Pro with some calibration errors, images of the extract and the full image uploaded in the drive.
