### ISSUE TITLE
Add Soil Organic carbon test 

### ISSUE THREAD

**Issue by NagarajUdupa7** [foundation-for-environmental-monitoring/ffem-lite#100]

**Comment by NagarajUdupa7** [comment]
The concentration points are 0, 0.5, 1.0, 2.0

**Comment by srijana-ya** [comment]
@PradeepBalkunde @sushantcaddisfly  need fertilizer recommendation for Organic Carbon standard points for ffem lite

**Comment by srijana-ya** [comment]
0 - 0.4 % = **Low**
0.41 - 0.8% = **Medium**
>0.81 =  **High**
