### ISSUE TITLE
Add Soil Phosphorus test , Soil Potassium, Soil pH, Soil Nitrogen , Soil Ammonia tests

### ISSUE THREAD

**Issue by NagarajUdupa7** [foundation-for-environmental-monitoring/ffem-lite#101]
The concentration points are 0, 0.5, 10, 20, 30ppm

**Comment by srijana-ya** [comment]
Phosphorous:
0-5.8 = Low
5.9 - 9.1 = Medium
>9.1 = High

**Comment by srijana-ya** [comment]
Risk Indication/fertilizer recommendations pending

**Comment by srijana-ya** [comment]
Risk indicating values for some parameters are higher than the assigned standard values. The indicating values correlate with the result obtained after undergoing the multiplication factor
