### ISSUE TITLE
Add Nitrite test, change Ammonia standard points, add Dissolved Oxygen test

### ISSUE THREAD

**Issue by srijana-ya** [foundation-for-environmental-monitoring/ffem-lite#115]

**Comment by srijana-ya** [comment]
Ranges:
Nitrite : 0, 0.05, 0.1, 0.25, 0.5
Ammonia: 0, 0.25, 0.5, 1.0, 2.0, 4.0, 8.0
Dissolved Oxygen (Standard points to be fixed)

**Comment by shreyas8712** [comment]
Risk Indication:
Nitrate: Safe <0-0.25 Unsafe >0.25
Ammonia: Safe<0-1 Unsafe > 1
Dissolved Oxygen: Good>4 Bad <4
