### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by srijana-ya** [foundation-for-environmental-monitoring/ffem-lite#12]
Errors while testing for residual chlorine
- With the new portrait mode, the error is always shown as "Bad Lighting" in Redmi Note 6 Pro and the image so received is sliced into half, images of which has been uploaded on the Test folder(Cl_RedmiNote6Pro_std_BadLighting). 
    To be noted:  The bar-code has never been detected by this phone and the capture button is being used while analyzing as of now.
-The app is also continuously crashing once in a while on Samsung On5 and Redmi Note 6 pro.

**Comment by nhternup** [comment]
Moved to Issue #10
