### ISSUE TITLE
Add new parameter: Fluoride - High Range

### ISSUE THREAD

**Issue by srijana-ya** [foundation-for-environmental-monitoring/ffem-lite#14]
High Range Fluoride with concentrations from 0.5 - 5.5 (0.5, 1.5, 2.5, 3.5, 4.5, 5.5) mg/l to be added

**Comment by srijana-ya** [comment]
High Range Fluoride concentration has to start from 0 - 5 (0, 1, 2, 3, 4, 5) mg/l  instead of 0.5 - 5.5 mg/l.

**Comment by nhternup** [comment]
Parameter name could be: 
Fluoride - High Range
