### ISSUE TITLE
Integration sample

### ISSUE THREAD

**Issue by aadvaark** [foundation-for-environmental-monitoring/ffem-lite#140]
Will ffem-lite / match work with the integration sample?

**Comment by nhternup** [comment]
Yes it should work
We have to decide on parameter id formats though
We had
WC-FM-F for ffem Lite
WC-HD-F for HD Pro

We may need 2 letter codes for Match and Compost
Unless we decide to base the 2 letter codes on reagents
Or add another 2 letter code for reagent...
