### ISSUE TITLE
Add a screen to display the result information

### ISSUE THREAD

**Issue by srijana-ya** [foundation-for-environmental-monitoring/ffem-lite#20]
Information to be displayed on result screen:

1. The title of the test (Fluoride) 
1. The result value (1.5)
1. The result unit (mg/l)
1. Risk factor (ex. for Fluoride: Low [0 - 0.9], Medium [1 - 2.9] or High [3+])
1. Margin of error
1. Button: **Submit Result**

**Comment by nhternup** [comment]
![resultscreen](https://user-images.githubusercontent.com/4124856/79260786-74f66180-7eac-11ea-8a41-2b83995d8860.png)

**Comment by srijana-ya** [comment]
Tested
