### ISSUE TITLE
Display risk indicator on the result screen

### ISSUE THREAD

**Issue by nhternup** [foundation-for-environmental-monitoring/ffem-lite#23]
Risk indicator example for Fluoride:

**Fluoride**
- Low: 0  to < 1 
- Medium:  >= 1 to < 2.01
- High:  >= 2.01

**pH**

- High: 0  to < 6
- Medium:  >= 6  to < 6.5
- Low:  >= 6.5 to < 8.5
- Medium: >= 8.5 to < 9
- High: >= 9

**Residual Chlorine**

- Insufficient: 0 to < 0.2
- Sufficient: >= 0.2 to < 0.81
- Too high:  >= 0.81

**Comment by srijana-ya** [comment]
Updated Risk Indicator for Fluoride:

Low: 0 to < 1
Medium: >= 1 to < 1.5
High: >= 1.5
