### ISSUE TITLE
Errors during swatch detection

### ISSUE THREAD

**Issue by saurabhlevin** [foundation-for-environmental-monitoring/ffem-lite#5]
The swatch detection seems to be quite erratic, and tests are frequently giving errors as a result. this may be related to Issue #4 , but it's hard to say since it occurs on some phones that behave fine otherwise.

Some sample screenshots:
Moto G3:
![IMG_20191126_154502](https://user-images.githubusercontent.com/8445292/69623884-a4294500-1069-11ea-9a76-65f48a69a429.jpg)

Asus Zenfone 3:
![Screenshot_20191126-154306](https://user-images.githubusercontent.com/8445292/69623909-b1deca80-1069-11ea-93e0-3462b2e2e45e.jpg)
![Screenshot_20191126-154314](https://user-images.githubusercontent.com/8445292/69623912-b30ff780-1069-11ea-92d1-0d79861346e6.jpg)

Samsung A260G:
![Screenshot_20191126-154025](https://user-images.githubusercontent.com/8445292/69624047-ef435800-1069-11ea-848c-502f677f3ff3.jpg)

Honor LND-AL30:
![Screenshot_20191126-153741](https://user-images.githubusercontent.com/8445292/69624112-126e0780-106a-11ea-9570-2dcded478bc8.jpg)
![Screenshot_20191126-153711](https://user-images.githubusercontent.com/8445292/69624113-126e0780-106a-11ea-94de-27a31b4ebbdb.jpg)

**Comment by nhternup** [comment]
Moved to #10
