### ISSUE TITLE
Errors with the new "Select existing image for analysis" update

### ISSUE THREAD

**Issue by srijana-ya** [foundation-for-environmental-monitoring/ffem-lite#6]
1. The app crashes while using the 'Select existing image for analysis' update, in the following phones:    
Samsung A2  
Honor LND-AL30   
Redmi Note 6 Pro    
Samsung J2

2. 3/5 phones which did give results with this update took about 2-6 mins to do so, all of which were errors.

![Screenshot_20191203-140118](https://user-images.githubusercontent.com/58282829/70045470-2bd2fe80-15ea-11ea-8a99-67ec1494e2b7.png)
![Screenshot_20191203-140050](https://user-images.githubusercontent.com/58282829/70045471-2bd2fe80-15ea-11ea-928c-519180e828f6.jpg)

**Comment by nhternup** [comment]
Would be good to keep all the images we are using for testing in one place. I will create a folder in google drive and upload the images I am using for testing there. Please use/add to them as required. (Folder -> ffem Lite/Test images)
