### ISSUE TITLE
Residual Chlorine test does not produce any result.

### ISSUE THREAD

**Issue by srijana-ya** [foundation-for-environmental-monitoring/ffem-lite#9]
The test for residual chlorine did not give any Euclidean value. 0 and 0.5 ppm was done for 3 phones which did not give any result. The pictures of which have been uploaded in the test file in the drive.

**Comment by nhternup** [comment]
The Residual chlorine will not work as the dimensions of the color card have been changed. The width of the cards are smaller compared to the older cards. The app is expecting the wider color cards and so will not work. This change will be accounted for in the next version.

**Comment by srijana-ya** [comment]
By older cards, are you referring to the 5x5 boxes that we had before and the way the app was programmed to recognize that?

**Comment by nhternup** [comment]
The 1 x 5. but card dimensions were not changed in the sense that the sides had blank white space.   Anyway in the next version new dimensions will be incorporated.
